// rollup-react-demo/src/App.tsx
import React, { Suspense, lazy, useState } from 'react';
import Button from '@/components/Button';
import rollupSvg from '@/assets/rollup.svg'

const About = lazy(() => delayDemo(import('@/components/About'), 2000));

//添加一个固定延迟，以便看到加载效果
async function delayDemo(promise: Promise<any>, delay: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, delay);
  }).then(() => promise);
}

const App = () => {
  const [show, setShow] = useState(false);
  return (
    <>
      <Button type="primary" onClick={() => setShow(!show)}>切换</Button>
      {show && (
        <Suspense fallback={<>loading...</>}>
          <About />
        </Suspense>
      )}
       <img src={rollupSvg} />
    </>
  );
};
export default App;

// rollup-vue-demo/src/App.vue
<script setup>
import { ref } from 'vue';
import Button from './components/Button.vue';

const show = ref(false)
</script>
<template>
  <img src="@/assets/rollup.svg" alt="">
  <Button size="small" @click="show = !show">切换</Button>
  <Button type="danger" size="small">danger</Button>
  <Button v-if="show" size="middle" type="primary">primary</Button>
</template>
<style lang="scss" scoped>
img {
  height: 400px;
  width: 300px;
}
</style>
